# Generated by Django 4.1.7 on 2023-04-01 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recurso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recurso',
        ),
    ]
